"""Update Contact us inquiry form

Revision ID: 279656811614
Revises: ca9eb99df2b8
Create Date: 2024-12-10 16:43:27.533537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279656811614'
down_revision = 'ca9eb99df2b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_inquiry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_location', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('interested_product', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('current_solution', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('inquiry_reason', sa.Text(), nullable=True))
        batch_op.alter_column('job_details',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_inquiry', schema=None) as batch_op:
        batch_op.alter_column('job_details',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('inquiry_reason')
        batch_op.drop_column('current_solution')
        batch_op.drop_column('interested_product')
        batch_op.drop_column('company_location')

    # ### end Alembic commands ###
